apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: testing
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 433474711752.dkr.ecr.us-east-2.amazonaws.com/eks-test-1:latest
        ports:
        - containerPort: 80
        env:
          - name: node
            value: stag
